<a href="https://colab.research.google.com/github/rawhul05/My-first-repository/blob/main/Pandas_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pfizer Drug Stability Data

Imagine you are working as a Data Scientist supporting a drug development team at Pfizer. The team is running stability tests on several drugs, recording temperature and pressure at hourly intervals every day. These readings determine whether a drug stays stable under different conditions, so getting the data right is critical.

The drug-testing team needs to prepare raw hourly readings for analysis - calculate daily temperature and pressure summaries, classify temperatures into bands, identify missing readings, and examine selected drugs. How can we restructure and process the data to support these tasks?

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
!gdown 173A59xh2mnpmljCCB9bhC4C5eP2IS6qZ

Downloading...
From: https://drive.google.com/uc?id=173A59xh2mnpmljCCB9bhC4C5eP2IS6qZ
To: /content/Pfizer_1.csv
100% 1.51k/1.51k [00:00<00:00, 6.30MB/s]

In [ ]:
import pandas as pd

data = pd.read_csv('Pfizer_1.csv')
data

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,NaN,NaN,7.0,NaN,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,NaN,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,NaN,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,NaN,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,NaN,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,NaN,11.0,12,12.0,11.0,NaN,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,NaN,15.0,15,15.0,15.0,NaN,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,NaN,13.0,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,NaN,9.0,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [ ]:
data.shape

(18, 15)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       18 non-null     object
 1   Drug_Name  18 non-null     object
 2   Parameter  18 non-null     object
 3   1:30:00    16 non-null     float64
 4   2:30:00    16 non-null     float64
 5   3:30:00    12 non-null     float64
 6   4:30:00    14 non-null     float64
 7   5:30:00    16 non-null     float64
 8   6:30:00    18 non-null     int64
 9   7:30:00    16 non-null     float64
 10  8:30:00    14 non-null     float64
 11  9:30:00    16 non-null     float64
 12  10:30:00   18 non-null     int64
 13  11:30:00   16 non-null     float64
 14  12:30:00   18 non-null     int64
dtypes: float64(9), int64(3), object(3)
memory usage: 2.2+ KB

#Restructing technique

##Melt (Wide --> Long)

In [ ]:
pd.melt(data, id_vars = ['Date','Drug_Name','Parameter'])

           Date                Drug_Name    Parameter  variable  value
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00   23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00   12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00    NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00    NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00   24.0
..          ...                      ...          ...       ...    ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00   14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00   23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00   28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00   24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00   15.0

[216 rows x 5 columns]

In [ ]:
#Alternate
data.melt(id_vars = ['Date','Drug_Name','Parameter'])

           Date                Drug_Name    Parameter  variable  value
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00   23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00   12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00    NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00    NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00   24.0
..          ...                      ...          ...       ...    ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00   14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00   23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00   28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00   24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00   15.0

[216 rows x 5 columns]

In [ ]:
data_melt = data.melt(id_vars = ['Date','Drug_Name','Parameter'], var_name='time', value_name='reading')
data_melt

           Date                Drug_Name    Parameter      time  reading
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00     23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00     12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00      NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00      NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00     24.0
..          ...                      ...          ...       ...      ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00     14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00     23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00     28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00     24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00     15.0

[216 rows x 5 columns]

##Pivoting (Long --> Wide)

In [ ]:
data_melt.pivot(index=['Date','Drug_Name','Parameter'], columns='time', values='reading')

time                                            10:30:00  11:30:00  12:30:00  \
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure         18.0      19.0      20.0
                                   Temperature      20.0      20.0      21.0
           docetaxel injection     Pressure         26.0      29.0      28.0
                                   Temperature      23.0      25.0      25.0
           ketamine hydrochloride  Pressure          9.0       9.0      11.0
                                   Temperature      22.0      21.0      20.0
16-10-2020 diltiazem hydrochloride Pressure         24.0       NaN      27.0
                                   Temperature      40.0       NaN      42.0
           docetaxel injection     Pressure         28.0      29.0      30.0
                                   Temperature      56.0      57.0      58.0
           ketamine hydrochloride  Pressure         16.0      17.0      18.0
                                   Temperature      13.0      14.0      15.0
17-10-2020 diltiazem hydrochloride Pressure         11.0      13.0      14.0
                                   Temperature      14.0      11.0      10.0
           docetaxel injection     Pressure         28.0      29.0      28.0
                                   Temperature      21.0      22.0      23.0
           ketamine hydrochloride  Pressure         13.0      14.0      15.0
                                   Temperature      22.0      23.0      24.0

time                                            1:30:00  2:30:00  3:30:00  \
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure        12.0     13.0      NaN
                                   Temperature     23.0     22.0      NaN
           docetaxel injection     Pressure         NaN     22.0     22.0
                                   Temperature      NaN     17.0     18.0
           ketamine hydrochloride  Pressure         8.0      NaN      NaN
                                   Temperature     24.0      NaN      NaN
16-10-2020 diltiazem hydrochloride Pressure        18.0     19.0     20.0
                                   Temperature     34.0     35.0     36.0
           docetaxel injection     Pressure        23.0     24.0      NaN
                                   Temperature     46.0     47.0      NaN
           ketamine hydrochloride  Pressure        12.0     12.0     13.0
                                   Temperature      8.0      9.0     10.0
17-10-2020 diltiazem hydrochloride Pressure         3.0      4.0      4.0
                                   Temperature     20.0     19.0     19.0
           docetaxel injection     Pressure        20.0     22.0     22.0
                                   Temperature     12.0     13.0     14.0
           ketamine hydrochloride  Pressure         8.0      9.0     10.0
                                   Temperature     13.0     14.0     15.0

time                                            4:30:00  5:30:00  6:30:00  \
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure        11.0     13.0     14.0
                                   Temperature     21.0     21.0     22.0
           docetaxel injection     Pressure         NaN     22.0     23.0
                                   Temperature      NaN     17.0     18.0
           ketamine hydrochloride  Pressure         7.0      NaN      9.0
                                   Temperature     27.0      NaN     26.0
16-10-2020 diltiazem hydrochloride Pressure        21.0     22.0     23.0
                                   Temperature     36.0     37.0     38.0
           docetaxel injection     Pressure        25.0     26.0     27.0
                                   Temperature     48.0     48.0     49.0
           ketamine hydrochloride  Pressure         NaN     15.0     15.0
                                   Temperature      NaN     11.0     12.0
17-10-2020 diltiazem hydrochloride Pressure         4.0      6.0      8.0
                                   Temperature     18.0     17.0     16.0
           docetaxel injection     Pressure        22.0     22.0     23.0
                                   Temperature     15.0     16.0     17.0
           ketamine hydrochloride  Pressure        11.0     11.0     12.0
                                   Temperature     16.0     17.0     18.0

time                                            7:30:00  8:30:00  9:30:00
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure        16.0     16.0     24.0
                                   Temperature     23.0     21.0     22.0
           docetaxel injection     Pressure         NaN      NaN     27.0
                                   Temperature      NaN      NaN     23.0
           ketamine hydrochloride  Pressure        10.0     11.0     10.0
                                   Temperature     25.0     24.0     23.0
16-10-2020 diltiazem hydrochloride Pressure        24.0     25.0     25.0
                                   Temperature     37.0     38.0     39.0
           docetaxel injection     Pressure        28.0     29.0     28.0
                                   Temperature     50.0     52.0     55.0
           ketamine hydrochloride  Pressure        15.0     15.0      NaN
                                   Temperature     12.0     11.0      NaN
17-10-2020 diltiazem hydrochloride Pressure         9.0      NaN      9.0
                                   Temperature     15.0      NaN     13.0
           docetaxel injection     Pressure        25.0     26.0     27.0
                                   Temperature     18.0     19.0     20.0
           ketamine hydrochloride  Pressure        12.0     11.0     12.0
                                   Temperature     19.0     20.0     21.0

In [ ]:
data_melt.pivot(index=['Date','Drug_Name','Parameter'], columns='time', values='reading').reset_index()

time,Date,Drug_Name,Parameter,10:30:00,11:30:00,12:30:00,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00
0,15-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,12.0,13.0,NaN,11.0,13.0,14.0,16.0,16.0,24.0
1,15-10-2020,diltiazem hydrochloride,Temperature,20.0,20.0,21.0,23.0,22.0,NaN,21.0,21.0,22.0,23.0,21.0,22.0
2,15-10-2020,docetaxel injection,Pressure,26.0,29.0,28.0,NaN,22.0,22.0,NaN,22.0,23.0,NaN,NaN,27.0
3,15-10-2020,docetaxel injection,Temperature,23.0,25.0,25.0,NaN,17.0,18.0,NaN,17.0,18.0,NaN,NaN,23.0
4,15-10-2020,ketamine hydrochloride,Pressure,9.0,9.0,11.0,8.0,NaN,NaN,7.0,NaN,9.0,10.0,11.0,10.0
5,15-10-2020,ketamine hydrochloride,Temperature,22.0,21.0,20.0,24.0,NaN,NaN,27.0,NaN,26.0,25.0,24.0,23.0
6,16-10-2020,diltiazem hydrochloride,Pressure,24.0,NaN,27.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,25.0
7,16-10-2020,diltiazem hydrochloride,Temperature,40.0,NaN,42.0,34.0,35.0,36.0,36.0,37.0,38.0,37.0,38.0,39.0
8,16-10-2020,docetaxel injection,Pressure,28.0,29.0,30.0,23.0,24.0,NaN,25.0,26.0,27.0,28.0,29.0,28.0
9,16-10-2020,docetaxel injection,Temperature,56.0,57.0,58.0,46.0,47.0,NaN,48.0,48.0,49.0,50.0,52.0,55.0
10,16-10-2020,ketamine hydrochloride,Pressure,16.0,17.0,18.0,12.0,12.0,13.0,NaN,15.0,15.0,15.0,15.0,NaN
11,16-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,8.0,9.0,10.0,NaN,11.0,12.0,12.0,11.0,NaN
12,17-10-2020,diltiazem hydrochloride,Pressure,11.0,13.0,14.0,3.0,4.0,4.0,4.0,6.0,8.0,9.0,NaN,9.0
13,17-10-2020,diltiazem hydrochloride,Temperature,14.0,11.0,10.0,20.0,19.0,19.0,18.0,17.0,16.0,15.0,NaN,13.0
14,17-10-2020,docetaxel injection,Pressure,28.0,29.0,28.0,20.0,22.0,22.0,22.0,22.0,23.0,25.0,26.0,27.0
15,17-10-2020,docetaxel injection,Temperature,21.0,22.0,23.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0
16,17-10-2020,ketamine hydrochloride,Pressure,13.0,14.0,15.0,8.0,9.0,10.0,11.0,11.0,12.0,12.0,11.0,12.0
17,17-10-2020,ketamine hydrochloride,Temperature,22.0,23.0,24.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0

In [ ]:
data_melt.head()

         Date                Drug_Name    Parameter     time  reading
0  15-10-2020  diltiazem hydrochloride  Temperature  1:30:00     23.0
1  15-10-2020  diltiazem hydrochloride     Pressure  1:30:00     12.0
2  15-10-2020      docetaxel injection  Temperature  1:30:00      NaN
3  15-10-2020      docetaxel injection     Pressure  1:30:00      NaN
4  15-10-2020   ketamine hydrochloride  Temperature  1:30:00     24.0

In [ ]:
data_tidy = data_melt.pivot(index=['Date','time','Drug_Name'], columns = 'Parameter', values = 'reading')

data_tidy

Parameter                                    Pressure  Temperature
Date       time     Drug_Name
15-10-2020 10:30:00 diltiazem hydrochloride      18.0         20.0
                    docetaxel injection          26.0         23.0
                    ketamine hydrochloride        9.0         22.0
           11:30:00 diltiazem hydrochloride      19.0         20.0
                    docetaxel injection          29.0         25.0
...                                               ...          ...
17-10-2020 8:30:00  docetaxel injection          26.0         19.0
                    ketamine hydrochloride       11.0         20.0
           9:30:00  diltiazem hydrochloride       9.0         13.0
                    docetaxel injection          27.0         20.0
                    ketamine hydrochloride       12.0         21.0

[108 rows x 2 columns]

In [ ]:
data_tidy = data_tidy.reset_index()
data_tidy

Parameter,Date,time,Drug_Name,Pressure,Temperature
0,15-10-2020,10:30:00,diltiazem hydrochloride,18.0,20.0
1,15-10-2020,10:30:00,docetaxel injection,26.0,23.0
2,15-10-2020,10:30:00,ketamine hydrochloride,9.0,22.0
3,15-10-2020,11:30:00,diltiazem hydrochloride,19.0,20.0
4,15-10-2020,11:30:00,docetaxel injection,29.0,25.0
...,...,...,...,...,...
103,17-10-2020,8:30:00,docetaxel injection,26.0,19.0
104,17-10-2020,8:30:00,ketamine hydrochloride,11.0,20.0
105,17-10-2020,9:30:00,diltiazem hydrochloride,9.0,13.0
106,17-10-2020,9:30:00,docetaxel injection,27.0,20.0
107,17-10-2020,9:30:00,ketamine hydrochloride,12.0,21.0

In [ ]:
data_tidy.columns

Index(['Date', 'time', 'Drug_Name', 'Pressure', 'Temperature'], dtype='object', name='Parameter')

In [ ]:
data_tidy.columns.name = None
data_tidy.head()

         Date      time                Drug_Name  Pressure  Temperature
0  15-10-2020  10:30:00  diltiazem hydrochloride      18.0         20.0
1  15-10-2020  10:30:00      docetaxel injection      26.0         23.0
2  15-10-2020  10:30:00   ketamine hydrochloride       9.0         22.0
3  15-10-2020  11:30:00  diltiazem hydrochloride      19.0         20.0
4  15-10-2020  11:30:00      docetaxel injection      29.0         25.0

#Pivot table

can we use pivot() to find the day-wise avg temperature for each drug?

In [ ]:
data_tidy.pivot(index=['Drug_Name'], columns=['Date'], values=['Temperature'])

ValueError: Index contains duplicate entries, cannot reshape

In [ ]:
# Calculate day-wise average temperature using pivot_table
data_tidy.pivot_table(index='Drug_Name', columns='Date', values='Temperature', aggfunc='mean')

Date                     15-10-2020  16-10-2020  17-10-2020
Drug_Name
diltiazem hydrochloride   21.454545   37.454545   15.636364
docetaxel injection       20.750000   51.454545   17.500000
ketamine hydrochloride    23.555556   11.500000   18.500000

In [ ]:
data_tidy.pivot_table(index='Drug_Name', columns='Date', values='Temperature', aggfunc='min')

Date                     15-10-2020  16-10-2020  17-10-2020
Drug_Name
diltiazem hydrochloride        20.0        34.0        10.0
docetaxel injection            17.0        46.0        12.0
ketamine hydrochloride         20.0         8.0        13.0

#Binning

In [ ]:
data_tidy

           Date      time                Drug_Name  Pressure  Temperature
0    15-10-2020  10:30:00  diltiazem hydrochloride      18.0         20.0
1    15-10-2020  10:30:00      docetaxel injection      26.0         23.0
2    15-10-2020  10:30:00   ketamine hydrochloride       9.0         22.0
3    15-10-2020  11:30:00  diltiazem hydrochloride      19.0         20.0
4    15-10-2020  11:30:00      docetaxel injection      29.0         25.0
..          ...       ...                      ...       ...          ...
103  17-10-2020   8:30:00      docetaxel injection      26.0         19.0
104  17-10-2020   8:30:00   ketamine hydrochloride      11.0         20.0
105  17-10-2020   9:30:00  diltiazem hydrochloride       9.0         13.0
106  17-10-2020   9:30:00      docetaxel injection      27.0         20.0
107  17-10-2020   9:30:00   ketamine hydrochloride      12.0         21.0

[108 rows x 5 columns]

In [ ]:
data_tidy['Temperature'].min(), data_tidy['Temperature'].max()

(8.0, 58.0)

In [ ]:
temp_points = [5,20, 35, 50, 60]
temp_labels = ['low','medium','high','very_high']

data_tidy['temp_cat'] = pd.cut(data_tidy['Temperature'], bins=temp_points, labels=temp_labels)
data_tidy

,Date,time,Drug_Name,Pressure,Temperature,temp_cat
0,15-10-2020,10:30:00,diltiazem hydrochloride,18.0,20.0,low
1,15-10-2020,10:30:00,docetaxel injection,26.0,23.0,medium
2,15-10-2020,10:30:00,ketamine hydrochloride,9.0,22.0,medium
3,15-10-2020,11:30:00,diltiazem hydrochloride,19.0,20.0,low
4,15-10-2020,11:30:00,docetaxel injection,29.0,25.0,medium
...,...,...,...,...,...,...
103,17-10-2020,8:30:00,docetaxel injection,26.0,19.0,low
104,17-10-2020,8:30:00,ketamine hydrochloride,11.0,20.0,low
105,17-10-2020,9:30:00,diltiazem hydrochloride,9.0,13.0,low
106,17-10-2020,9:30:00,docetaxel injection,27.0,20.0,low
107,17-10-2020,9:30:00,ketamine hydrochloride,12.0,21.0,medium

In [ ]:
data_tidy['temp_cat'].value_counts()

temp_cat
low          45
medium       30
high         15
very_high     5
Name: count, dtype: int64

#Handle Missing Values

In [ ]:
#import pandas as pd

data = pd.read_csv('Pfizer_1.csv')

data_melt = pd.melt(data, id_vars=['Date', 'Drug_Name', 'Parameter'],
                     var_name="time", value_name='reading')

data_tidy = data_melt.pivot(index=['Date', 'time', 'Drug_Name'],
                            columns='Parameter', values='reading')
data_tidy = data_tidy.reset_index()
data_tidy.columns.name = None

In [ ]:
data.head(5)

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20

In [ ]:
data_melt.head(1)

         Date                Drug_Name    Parameter     time  reading
0  15-10-2020  diltiazem hydrochloride  Temperature  1:30:00     23.0

In [ ]:
data_tidy.head(1)

         Date      time                Drug_Name  Pressure  Temperature
0  15-10-2020  10:30:00  diltiazem hydrochloride      18.0         20.0

#NaN vs None

In [ ]:
type(None)

NoneType

In [ ]:
import numpy as np

type(np.nan)

float

In [ ]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

For a numeric Series, Pandas changes None to NaN. Both become the same thing internally - every value in the output prints as NaN, and you can no longer tell which ones started out as None.

In [ ]:
pd.Series(["1","np.nan","2",np.nan])

0         1
1    np.nan
2         2
3       NaN
dtype: object

Three of these four values are strings - "1", "np.nan" (yes, literally the text), and "2" - and only the unquoted np.nan is an actual missing value, so it is the one entry that prints as NaN.

In [ ]:
pd.Series(["1","2",None,np.nan])

0       1
1       2
2    None
3     NaN
dtype: object

#Detect Missing Values

In [ ]:
data.isna().head()

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,True,False,False,True,True,False,False,False,False
3,False,False,False,True,False,False,True,False,False,True,True,False,False,False,False
4,False,False,False,False,True,True,False,True,False,False,False,False,False,False,False

In [ ]:
pd.isnull

In [ ]:
pd.isna

In [ ]:
data.isna().sum() #axis = 0 (vertical)

Date         0
Drug_Name    0
Parameter    0
1:30:00      2
2:30:00      2
3:30:00      6
4:30:00      4
5:30:00      2
6:30:00      0
7:30:00      2
8:30:00      4
9:30:00      2
10:30:00     0
11:30:00     2
12:30:00     0
dtype: int64

In [ ]:
data.isna().sum(axis=1)

0     1
1     1
2     4
3     4
4     3
5     3
6     1
7     1
8     1
9     1
10    2
11    2
12    1
13    1
14    0
15    0
16    0
17    0
dtype: int64

#Remove and Fill the missing values

##Remove Missing Values

In [ ]:
data

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,NaN,NaN,7.0,NaN,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,NaN,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,NaN,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,NaN,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,NaN,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,NaN,11.0,12,12.0,11.0,NaN,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,NaN,15.0,15,15.0,15.0,NaN,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,NaN,13.0,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,NaN,9.0,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [ ]:
data.dropna()

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [ ]:
data.dropna(axis=1)

,Date,Drug_Name,Parameter,6:30:00,10:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,22,20,21
1,15-10-2020,diltiazem hydrochloride,Pressure,14,18,20
2,15-10-2020,docetaxel injection,Temperature,18,23,25
3,15-10-2020,docetaxel injection,Pressure,23,26,28
4,15-10-2020,ketamine hydrochloride,Temperature,26,22,20
5,15-10-2020,ketamine hydrochloride,Pressure,9,9,11
6,16-10-2020,diltiazem hydrochloride,Temperature,38,40,42
7,16-10-2020,diltiazem hydrochloride,Pressure,23,24,27
8,16-10-2020,docetaxel injection,Temperature,49,56,58
9,16-10-2020,docetaxel injection,Pressure,27,28,30
10,16-10-2020,ketamine hydrochloride,Temperature,12,13,15
11,16-10-2020,ketamine hydrochloride,Pressure,15,16,18
12,17-10-2020,diltiazem hydrochloride,Temperature,16,14,10
13,17-10-2020,diltiazem hydrochloride,Pressure,8,11,14
14,17-10-2020,docetaxel injection,Temperature,17,21,23
15,17-10-2020,docetaxel injection,Pressure,23,28,28
16,17-10-2020,ketamine hydrochloride,Temperature,18,22,24
17,17-10-2020,ketamine hydrochloride,Pressure,12,13,15

#Fill the missing values

#Replacing missing values <--> Imputation of missing values

In [ ]:
data.fillna(0)

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,0.0,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,0.0,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,0.0,17.0,18.0,0.0,17.0,18,0.0,0.0,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,0.0,22.0,22.0,0.0,22.0,23,0.0,0.0,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,0.0,0.0,27.0,0.0,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,0.0,0.0,7.0,0.0,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,0.0,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,0.0,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,0.0,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,0.0,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,0.0,11.0,12,12.0,11.0,0.0,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,0.0,15.0,15,15.0,15.0,0.0,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,0.0,13.0,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,0.0,9.0,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [ ]:
data['3:30:00'] = data['3:30:00'].fillna(data['3:30:00'].mean())
data['3:30:00']

0     16.916667
1     16.916667
2     18.000000
3     22.000000
4     16.916667
5     16.916667
6     36.000000
7     20.000000
8     16.916667
9     16.916667
10    10.000000
11    13.000000
12    19.000000
13     4.000000
14    14.000000
15    22.000000
16    15.000000
17    10.000000
Name: 3:30:00, dtype: float64

mode - frequency count (categorical columns)

mean/median - continuous columns

#String Methods

In [ ]:
data_tidy.head()

         Date      time                Drug_Name  Pressure  Temperature
0  15-10-2020  10:30:00  diltiazem hydrochloride      18.0         20.0
1  15-10-2020  10:30:00      docetaxel injection      26.0         23.0
2  15-10-2020  10:30:00   ketamine hydrochloride       9.0         22.0
3  15-10-2020  11:30:00  diltiazem hydrochloride      19.0         20.0
4  15-10-2020  11:30:00      docetaxel injection      29.0         25.0

In [ ]:
data_tidy.loc[data_tidy['Drug_Name'].str.contains('hydrochloride')].head()

         Date      time                Drug_Name  Pressure  Temperature
0  15-10-2020  10:30:00  diltiazem hydrochloride      18.0         20.0
2  15-10-2020  10:30:00   ketamine hydrochloride       9.0         22.0
3  15-10-2020  11:30:00  diltiazem hydrochloride      19.0         20.0
5  15-10-2020  11:30:00   ketamine hydrochloride       9.0         21.0
6  15-10-2020  12:30:00  diltiazem hydrochloride      20.0         21.0

In [ ]:
data_tidy['Date'].str.split('-') #accessor

0      [15, 10, 2020]
1      [15, 10, 2020]
2      [15, 10, 2020]
3      [15, 10, 2020]
4      [15, 10, 2020]
            ...
103    [17, 10, 2020]
104    [17, 10, 2020]
105    [17, 10, 2020]
106    [17, 10, 2020]
107    [17, 10, 2020]
Name: Date, Length: 108, dtype: object

In [ ]:
data_tidy['Date'].str.split('-').apply(lambda x:x[0])

0      15
1      15
2      15
3      15
4      15
       ..
103    17
104    17
105    17
106    17
107    17
Name: Date, Length: 108, dtype: object

#Datetime values

In [ ]:
data_tidy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         108 non-null    object
 1   time         108 non-null    object
 2   Drug_Name    108 non-null    object
 3   Pressure     95 non-null     float64
 4   Temperature  95 non-null     float64
dtypes: float64(2), object(3)
memory usage: 4.3+ KB

In [ ]:
data_tidy['timestamp'] = data_tidy['Date'] + ' ' + data_tidy['time']
data_tidy.drop(['Date','time'],axis=1, inplace=True)
data_tidy.head()

                 Drug_Name  Pressure  Temperature            timestamp
0  diltiazem hydrochloride      18.0         20.0  15-10-2020 10:30:00
1      docetaxel injection      26.0         23.0  15-10-2020 10:30:00
2   ketamine hydrochloride       9.0         22.0  15-10-2020 10:30:00
3  diltiazem hydrochloride      19.0         20.0  15-10-2020 11:30:00
4      docetaxel injection      29.0         25.0  15-10-2020 11:30:00

In [ ]:
data_tidy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Drug_Name    108 non-null    object
 1   Pressure     95 non-null     float64
 2   Temperature  95 non-null     float64
 3   timestamp    108 non-null    object
dtypes: float64(2), object(2)
memory usage: 3.5+ KB

In [ ]:
data_tidy['timestamp'] = pd.to_datetime(data_tidy['timestamp'])
data_tidy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Drug_Name    108 non-null    object
 1   Pressure     95 non-null     float64
 2   Temperature  95 non-null     float64
 3   timestamp    108 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 3.5+ KB

In [ ]:
ts = data_tidy['timestamp'][0]
ts

Timestamp('2020-10-15 10:30:00')

In [ ]:
ts.year, ts.month, ts.day, ts.hour, ts.minute, ts.second

(2020, 10, 15, 10, 30, 0)

In [ ]:
data_tidy['timestamp'].dt

In [ ]:
data_tidy['timestamp'].dt.year

0      2020
1      2020
2      2020
3      2020
4      2020
       ...
103    2020
104    2020
105    2020
106    2020
107    2020
Name: timestamp, Length: 108, dtype: int32

In [ ]:
ts

Timestamp('2020-10-15 10:30:00')

In [ ]:
ts.strftime('%Y')

'2020'

In [ ]:
ts.strftime('%m-%d')

'10-15'

#Writing to a file

In [ ]:
data_tidy.to_csv('Pfizer_tidy.csv', index=False)