<a href="https://colab.research.google.com/github/rawhul05/My-first-repository/blob/main/Pandas_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Loading datasets

In [ ]:
import warnings

warnings.filterwarnings("ignore",category=DeprecationWarning)
warnings.filterwarnings("ignore",category=FutureWarning)


File 1 (movies): movies.csv - https://drive.google.com/file/d/1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd/view?usp=sharing

File 2 (directors): directors.csv - https://drive.google.com/file/d/1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm/view?usp=sharing

In [ ]:
!pip install --upgrade gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.13/dist-packages (5.2.2)
Collecting gdown
  Downloading gdown-6.4.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from gdown) (4.0.7)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.13/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.13/dist-packages (from gdown) (2.5.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4->gdown) (2.10)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4->gdown) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (3.20)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (2026.7.22)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (1.7.1)
Downloading gdown-6.4.1-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.8/50.8 kB 1.9 MB/s eta 0:00:00
Installing collected packages: gdown
  Attempting uninstall: gdown
    Found existing installation: gdown 5.2.2
    Uninstalling gdown-5.2.2:
      Successfully uninstalled gdown-5.2.2
Successfully installed gdown-6.4.1

In [ ]:
!gdown 1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
!gdown 1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm

Downloading...
From: https://drive.google.com/uc?id=1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
To: /content/movies.csv
100% 112k/112k [00:00<00:00, 62.5MB/s]
Using cookies from /root/.cache/gdown/cookies.txt
Downloading...
From: https://drive.google.com/uc?id=1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm
To: /content/directors.csv
100% 65.4k/65.4k [00:00<00:00, 47.1MB/s]

In [ ]:
import pandas as pd

In [ ]:
movies = pd.read_csv('movies.csv')
movies.head()
#directors = pd.read_csv('directors.csv')

,Unnamed: 0,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
4,5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday

In [ ]:
#Unnamed: 0

In [ ]:
movies = pd.read_csv('movies.csv', index_col=0)
movies

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...
4736,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday
4743,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday
4748,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday
4749,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday
4768,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday

In [ ]:
movies.shape

(1465, 11)

In [ ]:
directors = pd.read_csv('directors.csv',index_col=0)
directors.head()

       director_name    id gender
0      James Cameron  4762   Male
1     Gore Verbinski  4763   Male
2         Sam Mendes  4764   Male
3  Christopher Nolan  4765   Male
4     Andrew Stanton  4766   Male

In [ ]:
directors.shape

(2349, 3)

#Merge the two datasets

In [ ]:
print(movies['director_id'].count()) #movies.shape[0]

1465

In [ ]:
movies.shape[0]

1465

In [ ]:
movies['director_id'].nunique()

199

In [ ]:
directors['id'].nunique()

2349

In [ ]:
movies['director_id'].isin(directors['id'])

0       True
1       True
2       True
3       True
5       True
        ...
4736    True
4743    True
4748    True
4749    True
4768    True
Name: director_id, Length: 1465, dtype: bool

In [ ]:
print(movies['director_id'].isin(directors['id']).all())

True

In [ ]:
data = movies.merge(directors,how='left',left_on='director_id',right_on='id')
data

,id_x,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,id_y,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,James Cameron,4762,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday,Gore Verbinski,4763,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday,Sam Mendes,4764,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday,Christopher Nolan,4765,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday,Sam Raimi,4767,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday,Martin Scorsese,4809,Male
1461,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday,Kevin Smith,5369,Male
1462,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday,Uwe Boll,5148,Male
1463,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday,Richard Linklater,5535,Male
1464,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday,Robert Rodriguez,5097,NaN

In [ ]:
data.drop(['director_id','id_y'],axis=1, inplace=True)
data.head()

,id_x,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male

In [ ]:
data.rename(columns={'id_x':'id'},inplace=True)
data.head()

,id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,Male
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,Male
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,Male
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,Male
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,Male

#Apply()

In [ ]:
def encode(data):
  if data == "Male":
    return 0
  else:
    return 1

In [ ]:
data['gender'] = data['gender'].apply(encode)
data

,id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,0
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,0
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,0
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,0
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,0
1461,48370,27000,19,3151130,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,0
1462,48375,0,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,0
1463,48376,0,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,0
1464,48395,220000,14,2040920,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,1

In [ ]:
#Applying a function to multiple columns

In [ ]:
data[['revenue','budget']].apply(sum) #default is axis =0

revenue    209866997305
budget      70353617179
dtype: int64

In [ ]:
data[['revenue','budget']].apply(sum, axis = 1)

0       3024965087
1       1261000000
2       1125674609
3       1334939099
4       1148871626
           ...
1460        321952
1461       3178130
1462             0
1463             0
1464       2260920
Length: 1465, dtype: int64

In [ ]:
#Calculate profit

In [ ]:
def prof(x):
  return x['revenue'] - x['budget']

data['profit'] = data[['revenue','budget']].apply(prof, axis = 1)
data

,id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,0,2550965087
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,0,661000000
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,0,635674609
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,0,834939099
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,0,632871626
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,0,321952
1461,48370,27000,19,3151130,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,0,3124130
1462,48375,0,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,0,0
1463,48376,0,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,0,0
1464,48395,220000,14,2040920,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,1,1820920

#Group Based Aggregation

In [ ]:
data.groupby('director_name')

In [ ]:
data.groupby('director_name').ngroups

199

In [ ]:
data.groupby('director_name').groups

{'Adam McKay': [176, 323, 366, 505, 839, 916], 'Adam Shankman': [265, 300, 350, 404, 458, 843, 999, 1231], 'Alejandro González Iñárritu': [106, 749, 1015, 1034, 1077, 1405], 'Alex Proyas': [95, 159, 514, 671, 873], 'Alexander Payne': [793, 1006, 1101, 1211, 1281], 'Andrew Adamson': [11, 43, 328, 501, 947], 'Andrew Niccol': [533, 603, 701, 722, 1439], 'Andrzej Bartkowiak': [349, 549, 754, 911, 924], 'Andy Fickman': [517, 681, 909, 926, 973, 1023], 'Andy Tennant': [314, 320, 464, 593, 676, 885], 'Ang Lee': [99, 134, 748, 840, 1089, 1110, 1132, 1184], 'Anne Fletcher': [610, 650, 736, 789, 1206], 'Antoine Fuqua': [310, 338, 424, 467, 576, 808, 818, 1105], 'Atom Egoyan': [946, 1128, 1164, 1194, 1347, 1416], 'Barry Levinson': [313, 319, 471, 594, 878, 898, 1013, 1037, 1082, 1143, 1185, 1345, 1378], 'Barry Sonnenfeld': [13, 48, 90, 205, 591, 778, 783], 'Ben Stiller': [209, 212, 547, 562, 850], 'Bill Condon': [102, 307, 902, 1233, 1381], 'Bobby Farrelly': [352, 356, 481, 498, 624, 630, 654, 806, 928, 972, 1111], 'Brad Anderson': [1163, 1197, 1350, 1419, 1430], 'Brett Ratner': [24, 39, 188, 207, 238, 292, 405, 456, 920], 'Brian De Palma': [228, 255, 318, 439, 747, 905, 919, 1088, 1232, 1261, 1317, 1354], 'Brian Helgeland': [512, 607, 623, 742, 933], 'Brian Levant': [418, 449, 568, 761, 860, 1003], 'Brian Robbins': [416, 441, 669, 962, 988, 1115], 'Bryan Singer': [6, 32, 33, 44, 122, 216, 297, 1326], 'Cameron Crowe': [335, 434, 488, 503, 513, 698], 'Catherine Hardwicke': [602, 695, 724, 937, 1406, 1412], 'Chris Columbus': [117, 167, 204, 218, 229, 509, 656, 897, 996, 1086, 1129], 'Chris Weitz': [17, 500, 794, 869, 1202, 1267], 'Christopher Nolan': [3, 45, 58, 59, 74, 565, 641, 1341], 'Chuck Russell': [177, 410, 657, 1069, 1097, 1339], 'Clint Eastwood': [369, 426, 447, 482, 490, 520, 530, 535, 645, 727, 731, 786, 787, 899, 974, 986, 1167, 1190, 1313], 'Curtis Hanson': [494, 579, 606, 711, 733, 1057, 1310], 'Danny Boyle': [527, 668, 1083, 1085, 1126, 1168, 1287, 1385], 'Darren Aronofsky': [113, 751, 1187, 1328, 1363, 1458], 'Darren Lynn Bousman': [1241, 1243, 1283, 1338, 1440], 'David Ayer': [50, 273, 741, 1024, 1146, 1407], 'David Cronenberg': [541, 767, 994, 1055, 1254, 1268, 1334], 'David Fincher': [62, 213, 253, 383, 398, 478, 522, 555, 618, 785], 'David Gordon Green': [543, 862, 884, 927, 1376, 1418, 1432, 1459], 'David Koepp': [443, 644, 735, 1041, 1209], 'David Lynch': [583, 1161, 1264, 1340, 1456], 'David O. Russell': [422, 556, 609, 896, 982, 989, 1229, 1304], 'David R. Ellis': [582, 634, 756, 888, 934], 'David Zucker': [569, 619, 965, 1052, 1175], 'Dennis Dugan': [217, 260, 267, 293, 303, 718, 780, 977, 1247], 'Donald Petrie': [427, 507, 570, 649, 858, 894, 1106, 1331], 'Doug Liman': [52, 148, 251, 399, 544, 1318, 1451], 'Edward Zwick': [92, 182, 346, 566, 791, 819, 825], 'F. Gary Gray': [308, 402, 491, 523, 697, 833, 1272, 1380], 'Francis Ford Coppola': [487, 559, 622, 646, 772, 1076, 1155, 1253, 1312], 'Francis Lawrence': [63, 72, 109, 120, 679], 'Frank Coraci': [157, 249, 275, 451, 577, 599, 963], 'Frank Oz': [193, 355, 473, 580, 712, 813, 987], 'Garry Marshall': [329, 496, 528, 571, 784, 893, 1029, 1169], 'Gary Fleder': [518, 667, 689, 867, 981, 1165], 'Gary Winick': [258, 797, 798, 804, 1454], 'Gavin O'Connor': [820, 841, 939, 953, 1444], 'George A. Romero': [250, 1066, 1096, 1278, 1367, 1396], 'George Clooney': [343, 450, 831, 966, 1302], 'George Miller': [78, 103, 233, 287, 1250, 1403, 1450], 'Gore Verbinski': [1, 8, 9, 107, 119, 633, 1040], 'Guillermo del Toro': [35, 252, 419, 486, 1118], 'Gus Van Sant': [595, 1018, 1027, 1159, 1240, 1311, 1398], 'Guy Ritchie': [124, 215, 312, 1093, 1225, 1269, 1420], 'Harold Ramis': [425, 431, 558, 586, 788, 1137, 1166, 1325], 'Ivan Reitman': [274, 643, 816, 883, 910, 935, 1134, 1242], 'James Cameron': [0, 19, 170, 173, 344, 1100, 1320], 'James Ivory': [1125, 1152, 1180, 1291, 1293, 1390, 1397], 'James Mangold': [140, 141, 557, 560, 829, 845, 958, 1145], 'James Wan': [30, 617, 1002, 1047, 1337, 1417, 1424], 'Jan de Bont': [155, 224, 231, 270, 781], 'Jason Friedberg': [812, 1010, 1012, 1014, 1036], 'Jason Reitman': [792, 1092, 1213, 1295, 1299], 'Jaume Collet-Serra': [516, 540, 640, 725, 1011, 1189], 'Jay Roach': [195, 359, 389, 397, 461, 703, 859, 1072], 'Jean-Pierre Jeunet': [423, 485, 605, 664, 765], 'Joe Dante': [284, 525, 638, 1226, 1298, 1428], 'Joe Wright': [85, 432, 553, 803, 814, 855], 'Joel Coen': [428, 670, 691, 707, 721, 889, 906, 980, 1157, 1238, 1305], 'Joel Schumacher': [128, 184, 348, 484, 572, 614, 652, 764, 876, 886, 1108, 1230, 1280], 'John Carpenter': [537, 663, 686, 861, 938, 1028, 1080, 1102, 1329, 1371], 'John Glen': [601, 642, 801, 847, 864], 'John Landis': [524, 868, 1276, 1384, 1435], 'John Madden': [457, 882, 1020, 1249, 1257], 'John McTiernan': [127, 214, 244, 351, 534, 563, 648, 782, 838, 1074], 'John Singleton': [294, 489, 732, 796, 1120, 1173, 1316], 'John Whitesell': [499, 632, 763, 1119, 1148], 'John Woo': [131, 142, 264, 371, 420, 675, 1182], 'Jon Favreau': [46, 54, 55, 382, 759, 1346], 'Jon M. Chu': [100, 225, 810, 1099, 1186], 'Jon Turteltaub': [64, 180, 372, 480, 760, 846, 1171], 'Jonathan Demme': [277, 493, 1000, 1123, 1215], 'Jonathan Liebesman': [81, 143, 339, 1117, 1301], 'Judd Apatow': [321, 710, 717, 865, 881], 'Justin Lin': [38, 123, 246, 1437, 1447], 'Kenneth Branagh': [80, 197, 421, 879, 1094, 1277, 1288], 'Kenny Ortega': [412, 852, 1228, 1315, 1365], 'Kevin Reynolds': [53, 502, 639, 1019, 1059], ...}

In [ ]:
data.groupby('director_name').get_group('Alexander Payne')

,id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit
793,45163,30000000,19,105834556,About Schmidt,6.7,362,2002,Dec,Friday,Alexander Payne,1,75834556
1006,45699,20000000,40,177243185,The Descendants,6.7,934,2011,Sep,Friday,Alexander Payne,1,157243185
1101,46004,16000000,23,109502303,Sideways,6.9,478,2004,Oct,Friday,Alexander Payne,1,93502303
1211,46446,12000000,29,17654912,Nebraska,7.4,636,2013,Sep,Saturday,Alexander Payne,1,5654912
1281,46813,0,13,0,Election,6.7,270,1999,Apr,Friday,Alexander Payne,1,0

In [ ]:
data.groupby('director_name')['title'].count()

director_name
Adam McKay                      6
Adam Shankman                   8
Alejandro González Iñárritu     6
Alex Proyas                     5
Alexander Payne                 5
                               ..
Wes Craven                     10
Wolfgang Petersen               7
Woody Allen                    18
Zack Snyder                     7
Zhang Yimou                     6
Name: title, Length: 199, dtype: int64

In [ ]:
data.groupby('director_name')['title'].aggregate('count')

director_name
Adam McKay                      6
Adam Shankman                   8
Alejandro González Iñárritu     6
Alex Proyas                     5
Alexander Payne                 5
                               ..
Wes Craven                     10
Wolfgang Petersen               7
Woody Allen                    18
Zack Snyder                     7
Zhang Yimou                     6
Name: title, Length: 199, dtype: int64

Select director_name, count(title) from Data group by director_name;

In [ ]:
#data.groupby('director_name').count()

In [ ]:
data.groupby('director_name')['year'].aggregate(['min','max'])

                              min   max
director_name
Adam McKay                   2004  2015
Adam Shankman                2001  2012
Alejandro González Iñárritu  2000  2015
Alex Proyas                  1994  2016
Alexander Payne              1999  2013
...                           ...   ...
Wes Craven                   1984  2011
Wolfgang Petersen            1981  2006
Woody Allen                  1977  2013
Zack Snyder                  2004  2016
Zhang Yimou                  2002  2014

[199 rows x 2 columns]

In [ ]:
data['year'].aggregate(['min','max'])

min    1976
max    2016
Name: year, dtype: int64

#Quiz 2

In [ ]:
employee_data = pd.DataFrame({
    'emp_id': [101, 102, 103, 104, 105, 101, 102, 103, 104, 105],
    'monthly_rating': [4.5, 3.8, 4.2, 5.0, 4.0, 4.6, 3.9, 4.3, 4.9, 4.1],
    'bonus': [100, 150, 200, 250, 300, 120, 160, 210, 260, 310]
})

employee_data

   emp_id  monthly_rating  bonus
0     101             4.5    100
1     102             3.8    150
2     103             4.2    200
3     104             5.0    250
4     105             4.0    300
5     101             4.6    120
6     102             3.9    160
7     103             4.3    210
8     104             4.9    260
9     105             4.1    310

In [ ]:
employee_data.groupby('monthly_rating').mean()

                emp_id  bonus
monthly_rating
3.8              102.0  150.0
3.9              102.0  160.0
4.0              105.0  300.0
4.1              105.0  310.0
4.2              103.0  200.0
4.3              103.0  210.0
4.5              101.0  100.0
4.6              101.0  120.0
4.9              104.0  260.0
5.0              104.0  250.0

In [ ]:
#Option C

employee_data.groupby('emp_id')['monthly_rating'].mean()

emp_id
101    4.55
102    3.85
103    4.25
104    4.95
105    4.05
Name: monthly_rating, dtype: float64

#Quiz 4

In [ ]:
data.groupby['year'].agg({'vote_average': ['mean', 'min', 'max']})

TypeError: 'method' object is not subscriptable

In [ ]:
data.groupby('year').agg({'vote_average': ['mean', 'min', 'max']})

     vote_average
             mean  min  max
year
1976     7.633333  7.2  8.0
1977     6.900000  6.1  7.8
1978     7.020000  5.9  7.9
1979     7.025000  5.6  8.0
1980     7.187500  6.4  7.9
1981     6.927273  6.0  7.9
1982     6.810000  5.5  7.9
1983     6.666667  4.5  8.0
1984     6.760000  6.1  7.3
1985     6.885714  5.9  8.0
1986     6.809091  5.8  7.8
1987     6.991667  6.1  7.6
1988     6.692308  5.7  7.6
1989     6.750000  5.5  7.6
1990     6.661111  5.8  8.2
1991     7.100000  6.6  8.1
1992     6.640909  5.7  8.0
1993     7.144444  6.1  8.3
1994     6.596774  5.0  8.3
1995     6.509091  4.5  8.1
1996     6.384783  5.4  7.8
1997     6.552174  4.1  7.9
1998     6.442222  4.9  7.9
1999     6.384375  5.1  8.3
2000     6.347458  4.4  8.1
2001     6.217742  3.7  8.0
2002     6.359420  3.4  8.0
2003     6.115517  4.4  8.1
2004     6.427869  4.7  7.7
2005     6.229577  3.1  7.7
2006     6.212329  3.6  8.0
2007     6.307407  3.2  7.9
2008     6.268657  3.0  8.2
2009     6.190909  3.9  7.9
2010     6.223810  4.2  8.1
2011     6.098507  4.1  7.7
2012     6.216327  4.9  7.8
2013     6.315789  3.3  7.9
2014     6.313208  4.1  8.1
2015     6.141463  3.9  7.7
2016     5.915385  4.5  7.1

#Group based Filtering

Find the directors who have atleast one movie with budget greater than 100 M

In [ ]:
data_dir_budget = data.groupby('director_name')['budget'].max().reset_index()
data_dir_budget.head()

                 director_name     budget
0                   Adam McKay  100000000
1                Adam Shankman   80000000
2  Alejandro González Iñárritu  135000000
3                  Alex Proyas  140000000
4              Alexander Payne   30000000

In [ ]:
names = data_dir_budget.loc[data_dir_budget['budget'] > 100000000, "director_name"]
names

2      Alejandro González Iñárritu
3                      Alex Proyas
5                   Andrew Adamson
10                         Ang Lee
15                Barry Sonnenfeld
                  ...
185                      Tim Story
187                    Tom Shadyac
188                     Tom Tykwer
195              Wolfgang Petersen
197                    Zack Snyder
Name: director_name, Length: 79, dtype: object

In [ ]:
data.loc[data['director_name'].isin(names)]

,id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,0,2550965087
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,0,661000000
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,0,635674609
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,0,834939099
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,0,632871626
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1450,48267,400000,33,100000000,Mad Max,6.6,1213,1979,Apr,Thursday,George Miller,0,99600000
1451,48268,200000,13,4505922,Swingers,6.8,253,1996,Oct,Friday,Doug Liman,0,4305922
1452,48274,0,5,2611555,Three,6.3,31,2010,Dec,Thursday,Tom Tykwer,0,2611555
1458,48335,60000,27,3221152,Pi,7.1,586,1998,Jul,Friday,Darren Aronofsky,0,3161152
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,0,321952

In [ ]:
#Alternate approach

In [ ]:
data.groupby('director_name').filter(lambda x: x['budget'].max() > 100000000)

,id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,0,2550965087
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,0,661000000
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,0,635674609
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,0,834939099
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,0,632871626
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1450,48267,400000,33,100000000,Mad Max,6.6,1213,1979,Apr,Thursday,George Miller,0,99600000
1451,48268,200000,13,4505922,Swingers,6.8,253,1996,Oct,Friday,Doug Liman,0,4305922
1452,48274,0,5,2611555,Three,6.3,31,2010,Dec,Thursday,Tom Tykwer,0,2611555
1458,48335,60000,27,3221152,Pi,7.1,586,1998,Jul,Friday,Darren Aronofsky,0,3161152
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,0,321952

#Filter Groups on Multiple conditions

Filter out directors who have an avg budget > 50 M and total revenue > 100M

In [ ]:
data.groupby('director_name').filter(lambda x: x['budget'].mean() > 50000000 and x['revenue'].sum() >= 100000000)

,id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,0,2550965087
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,0,661000000
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,0,635674609
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,0,834939099
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,0,632871626
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1441,48162,0,7,773228,Bloody Sunday,7.2,53,2002,Jan,Wednesday,Paul Greengrass,0,773228
1443,48192,350000,35,29400000,The Evil Dead,7.3,894,1981,Oct,Thursday,Sam Raimi,0,29050000
1447,48231,0,3,0,Better Luck Tomorrow,6.5,27,2002,Jan,Saturday,Justin Lin,1,0
1450,48267,400000,33,100000000,Mad Max,6.6,1213,1979,Apr,Thursday,George Miller,0,99600000
1451,48268,200000,13,4505922,Swingers,6.8,253,1996,Oct,Friday,Doug Liman,0,4305922

#Using nunique() inside filter(lambda)

In [ ]:
data.head()

,id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,0,2550965087
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,0,661000000
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,0,635674609
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,0,834939099
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,0,632871626

Filter out directors who have directed more than 1 movies

In [ ]:
data.groupby('director_name').filter(lambda x: x['id'].nunique() > 1)

,id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,0,2550965087
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,0,661000000
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,0,635674609
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,0,834939099
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,0,632871626
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,0,321952
1461,48370,27000,19,3151130,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,0,3124130
1462,48375,0,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,0,0
1463,48376,0,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,0,0
1464,48395,220000,14,2040920,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,1,1820920

#Merge two aggregdated dataframes

In [ ]:
avg_df = data.groupby('director_name')['budget'].mean().reset_index()
avg_df

                   director_name        budget
0                     Adam McKay  5.691667e+07
1                  Adam Shankman  4.837500e+07
2    Alejandro González Iñárritu  3.333333e+07
3                    Alex Proyas  7.040000e+07
4                Alexander Payne  1.560000e+07
..                           ...           ...
194                   Wes Craven  2.338000e+07
195            Wolfgang Petersen  9.014286e+07
196                  Woody Allen  1.177778e+07
197                  Zack Snyder  1.228571e+08
198                  Zhang Yimou  2.083335e+07

[199 rows x 2 columns]

In [ ]:
cnt_df = data.groupby('director_name')['title'].count().reset_index()
cnt_df

                   director_name  title
0                     Adam McKay      6
1                  Adam Shankman      8
2    Alejandro González Iñárritu      6
3                    Alex Proyas      5
4                Alexander Payne      5
..                           ...    ...
194                   Wes Craven     10
195            Wolfgang Petersen      7
196                  Woody Allen     18
197                  Zack Snyder      7
198                  Zhang Yimou      6

[199 rows x 2 columns]

In [ ]:
combined= avg_df.merge(cnt_df, on ='director_name') #default = inner
combined

                   director_name        budget  title
0                     Adam McKay  5.691667e+07      6
1                  Adam Shankman  4.837500e+07      8
2    Alejandro González Iñárritu  3.333333e+07      6
3                    Alex Proyas  7.040000e+07      5
4                Alexander Payne  1.560000e+07      5
..                           ...           ...    ...
194                   Wes Craven  2.338000e+07     10
195            Wolfgang Petersen  9.014286e+07      7
196                  Woody Allen  1.177778e+07     18
197                  Zack Snyder  1.228571e+08      7
198                  Zhang Yimou  2.083335e+07      6

[199 rows x 3 columns]

#Group based Apply()

In [ ]:
def func(x):
  x["risky"] = x["budget"] - x["revenue"].mean() >=0
  return x

data_risky = data.groupby('director_name', group_keys=False).apply(func)
data_risky

,id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit,risky
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,0,2550965087,False
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,0,661000000,False
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,0,635674609,False
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,0,834939099,False
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,0,632871626,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,0,321952,False
1461,48370,27000,19,3151130,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,0,3124130,False
1462,48375,0,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,0,0,False
1463,48376,0,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,0,0,False
1464,48395,220000,14,2040920,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,1,1820920,False

In [ ]:
data.groupby('director_name', group_keys=True).apply(func) #default = True #ignore group keys

                       id     budget  popularity    revenue  \
director_name
Adam McKay    176   43882  100000000          24  170432927
              323   44151   72500000          12  162966177
              366   44236   65000000          22  128107642
              505   44503   50000000          38  173649015
              839   45301   28000000          57  133346506
...                   ...        ...         ...        ...
Zhang Yimou   590   44692        110           9          0
              604   44733   31000000          23  177394432
              1217  46460          0          21   92863945
              1223  46493          0           1          0
              1389  47489          0           6          0

                                                          title  vote_average  \
director_name
Adam McKay    176                                The Other Guys           6.1
              323   Talladega Nights: The Ballad of Ricky Bobby           6.2
              366                                 Step Brothers           6.5
              505             Anchorman 2: The Legend Continues           6.0
              839                                 The Big Short           7.3
...                                                         ...           ...
Zhang Yimou   590                    Curse of the Golden Flower           6.6
              604                                          Hero           7.2
              1217                      House of Flying Daggers           7.1
              1223             A Woman, a Gun and a Noodle Shop           4.8
              1389                                  Coming Home           6.9

                    vote_count  year month        day director_name  gender  \
director_name
Adam McKay    176         1383  2010   Aug     Friday    Adam McKay       0
              323          491  2006   Aug     Friday    Adam McKay       0
              366         1062  2008   Jul     Friday    Adam McKay       0
              505          923  2013   Dec  Wednesday    Adam McKay       0
              839         2607  2015   Dec     Friday    Adam McKay       0
...                        ...   ...   ...        ...           ...     ...
Zhang Yimou   590          203  2006   Dec   Thursday   Zhang Yimou       0
              604          635  2002   Dec   Thursday   Zhang Yimou       0
              1217         439  2004   May  Wednesday   Zhang Yimou       0
              1223          13  2009   Dec     Friday   Zhang Yimou       0
              1389          49  2014   May     Friday   Zhang Yimou       0

                       profit  risky
director_name
Adam McKay    176    70432927  False
              323    90466177  False
              366    63107642  False
              505   123649015  False
              839   105346506  False
...                       ...    ...
Zhang Yimou   590        -110  False
              604   146394432  False
              1217   92863945  False
              1223          0  False
              1389          0  False

[1465 rows x 14 columns]

How to find the risky movies?

In [ ]:
data_risky["risky"]

0       False
1       False
2       False
3       False
4       False
        ...
1460    False
1461    False
1462    False
1463    False
1464    False
Name: risky, Length: 1465, dtype: bool

In [ ]:
data_risky.loc[data_risky["risky"]]

,id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit,risky
7,43608,200000000,107,586090727,Quantum of Solace,6.1,2965,2008,Oct,Thursday,Marc Forster,0,386090727,True
12,43614,380000000,135,1045713802,Pirates of the Caribbean: On Stranger Tides,6.4,4948,2011,May,Saturday,Rob Marshall,0,665713802,True
15,43618,200000000,37,310669540,Robin Hood,6.2,1398,2010,May,Wednesday,Ridley Scott,0,110669540,True
20,43624,209000000,64,303025485,Battleship,5.5,2114,2012,Apr,Wednesday,Peter Berg,0,94025485,True
24,43630,210000000,3,459359555,X-Men: The Last Stand,6.3,3525,2006,May,Wednesday,Brett Ratner,0,249359555,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1347,47224,5000000,7,3263585,The Sweet Hereafter,6.8,103,1997,May,Wednesday,Atom Egoyan,0,-1736415,True
1349,47229,5000000,3,4842699,90 Minutes in Heaven,5.4,40,2015,Sep,Friday,Michael Polish,0,-157301,True
1351,47233,5000000,6,0,Light Sleeper,5.7,15,1992,Aug,Friday,Paul Schrader,1,-5000000,True
1356,47263,15000000,10,0,Dying of the Light,4.5,118,2014,Dec,Thursday,Paul Schrader,1,-15000000,True
1383,47453,3500000,4,0,In the Name of the King III,3.3,19,2013,Dec,Friday,Uwe Boll,0,-3500000,True

#Add the group level stats back to the original dataframe

In [ ]:
avg_budget = data.groupby('director_name')['budget'].mean().reset_index()
avg_budget

                   director_name        budget
0                     Adam McKay  5.691667e+07
1                  Adam Shankman  4.837500e+07
2    Alejandro González Iñárritu  3.333333e+07
3                    Alex Proyas  7.040000e+07
4                Alexander Payne  1.560000e+07
..                           ...           ...
194                   Wes Craven  2.338000e+07
195            Wolfgang Petersen  9.014286e+07
196                  Woody Allen  1.177778e+07
197                  Zack Snyder  1.228571e+08
198                  Zhang Yimou  2.083335e+07

[199 rows x 2 columns]

In [ ]:
avg_budget = avg_budget.rename(columns={'budget':'avg_director_budget'})
avg_budget

                   director_name  avg_director_budget
0                     Adam McKay         5.691667e+07
1                  Adam Shankman         4.837500e+07
2    Alejandro González Iñárritu         3.333333e+07
3                    Alex Proyas         7.040000e+07
4                Alexander Payne         1.560000e+07
..                           ...                  ...
194                   Wes Craven         2.338000e+07
195            Wolfgang Petersen         9.014286e+07
196                  Woody Allen         1.177778e+07
197                  Zack Snyder         1.228571e+08
198                  Zhang Yimou         2.083335e+07

[199 rows x 2 columns]

In [ ]:
data = data.merge(avg_budget, on='director_name')
data

,id,budget,popularity,revenue,title,vote_average,vote_count,year,month,day,director_name,gender,profit,avg_director_budget
0,43597,237000000,150,2787965087,Avatar,7.2,11800,2009,Dec,Thursday,James Cameron,0,2550965087,1.067000e+08
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,2007,May,Saturday,Gore Verbinski,0,661000000,1.581429e+08
2,43599,245000000,107,880674609,Spectre,6.3,4466,2015,Oct,Monday,Sam Mendes,0,635674609,9.485714e+07
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,2012,Jul,Monday,Christopher Nolan,0,834939099,1.256250e+08
4,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,2007,May,Tuesday,Sam Raimi,0,632871626,8.399545e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,48363,0,3,321952,The Last Waltz,7.9,64,1978,May,Monday,Martin Scorsese,0,321952,4.747895e+07
1461,48370,27000,19,3151130,Clerks,7.4,755,1994,Sep,Tuesday,Kevin Smith,0,3124130,1.200642e+07
1462,48375,0,7,0,Rampage,6.0,131,2009,Aug,Friday,Uwe Boll,0,0,2.170000e+07
1463,48376,0,3,0,Slacker,6.4,77,1990,Jul,Friday,Richard Linklater,0,0,1.089091e+07
1464,48395,220000,14,2040920,El Mariachi,6.6,238,1992,Sep,Friday,Robert Rodriguez,1,1820920,3.138875e+07

#Multi-Indexing

In [ ]:
!gdown 1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
!gdown 1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm

Using cookies from /root/.cache/gdown/cookies.txt
Downloading...
From: https://drive.google.com/uc?id=1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
To: /content/movies.csv
100% 112k/112k [00:00<00:00, 54.8MB/s]
Using cookies from /root/.cache/gdown/cookies.txt
Downloading...
From: https://drive.google.com/uc?id=1Ws-_s1fHZ9nHfGLVUQurbHDvStePlEJm
To: /content/directors.csv
100% 65.4k/65.4k [00:00<00:00, 56.9MB/s]

In [ ]:
movies = pd.read_csv('movies.csv', index_col=0)
#movies

directors = pd.read_csv('directors.csv',index_col=0)

In [ ]:
movies

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday
2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday
3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday
5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...
4736,48363,0,3,321952,The Last Waltz,7.9,64,4809,1978,May,Monday
4743,48370,27000,19,3151130,Clerks,7.4,755,5369,1994,Sep,Tuesday
4748,48375,0,7,0,Rampage,6.0,131,5148,2009,Aug,Friday
4749,48376,0,3,0,Slacker,6.4,77,5535,1990,Jul,Friday
4768,48395,220000,14,2040920,El Mariachi,6.6,238,5097,1992,Sep,Friday

In [ ]:
directors

          director_name    id gender
0         James Cameron  4762   Male
1        Gore Verbinski  4763   Male
2            Sam Mendes  4764   Male
3     Christopher Nolan  4765   Male
4        Andrew Stanton  4766   Male
...                 ...   ...    ...
2344      Shane Carruth  7106   Male
2345   Neill Dela Llana  7107    NaN
2346        Scott Smith  7108    NaN
2347        Daniel Hsia  7109   Male
2348   Brian Herzlinger  7110   Male

[2349 rows x 3 columns]

Who is the most productive director?

In [ ]:
data.groupby('director_name')['title'].count().sort_values(ascending=False)

director_name
Steven Spielberg    26
Martin Scorsese     19
Clint Eastwood      19
Woody Allen         18
Robert Rodriguez    16
                    ..
Stephen Daldry       5
Tom Tykwer           5
Tim Hill             5
Uwe Boll             5
Wayne Wang           5
Name: title, Length: 199, dtype: int64

In [ ]:
data_agg = data.groupby('director_name')[["year","title"]].aggregate({"year":['min','max'], "title":"count"})
data_agg

                             year       title
                              min   max count
director_name
Adam McKay                   2004  2015     6
Adam Shankman                2001  2012     8
Alejandro González Iñárritu  2000  2015     6
Alex Proyas                  1994  2016     5
Alexander Payne              1999  2013     5
...                           ...   ...   ...
Wes Craven                   1984  2011    10
Wolfgang Petersen            1981  2006     7
Woody Allen                  1977  2013    18
Zack Snyder                  2004  2016     7
Zhang Yimou                  2002  2014     6

[199 rows x 3 columns]

In [ ]:
data_agg.columns

MultiIndex([( 'year',   'min'),
            ( 'year',   'max'),
            ('title', 'count')],
           )

In [ ]:
data.columns

Index(['id', 'budget', 'popularity', 'revenue', 'title', 'vote_average',
       'vote_count', 'year', 'month', 'day', 'director_name', 'gender',
       'profit', 'avg_director_budget'],
      dtype='object')

In [ ]:
data_agg['year']

                              min   max
director_name
Adam McKay                   2004  2015
Adam Shankman                2001  2012
Alejandro González Iñárritu  2000  2015
Alex Proyas                  1994  2016
Alexander Payne              1999  2013
...                           ...   ...
Wes Craven                   1984  2011
Wolfgang Petersen            1981  2006
Woody Allen                  1977  2013
Zack Snyder                  2004  2016
Zhang Yimou                  2002  2014

[199 rows x 2 columns]

#Flatten the Multi-index columns

Approach 1

In [ ]:
data_agg.head()

                             year       title
                              min   max count
director_name
Adam McKay                   2004  2015     6
Adam Shankman                2001  2012     8
Alejandro González Iñárritu  2000  2015     6
Alex Proyas                  1994  2016     5
Alexander Payne              1999  2013     5

In [ ]:
data_agg.reset_index() #does not work

                   director_name  year       title
                                   min   max count
0                     Adam McKay  2004  2015     6
1                  Adam Shankman  2001  2012     8
2    Alejandro González Iñárritu  2000  2015     6
3                    Alex Proyas  1994  2016     5
4                Alexander Payne  1999  2013     5
..                           ...   ...   ...   ...
194                   Wes Craven  1984  2011    10
195            Wolfgang Petersen  1981  2006     7
196                  Woody Allen  1977  2013    18
197                  Zack Snyder  2004  2016     7
198                  Zhang Yimou  2002  2014     6

[199 rows x 4 columns]

In [ ]:
data_agg.columns

MultiIndex([( 'year',   'min'),
            ( 'year',   'max'),
            ('title', 'count')],
           )

In [ ]:
for col in data_agg.columns:
  print(col)

('year', 'min')
('year', 'max')
('title', 'count')

In [ ]:
col1 = ('year','min')
'_'.join(col1)

'year_min'

In [ ]:
data_agg.columns = ['_'.join(col) for col in data_agg.columns]

In [ ]:
data_agg.columns

Index(['year_min', 'year_max', 'title_count'], dtype='object')

In [ ]:
data_agg

                             year_min  year_max  title_count
director_name
Adam McKay                       2004      2015            6
Adam Shankman                    2001      2012            8
Alejandro González Iñárritu      2000      2015            6
Alex Proyas                      1994      2016            5
Alexander Payne                  1999      2013            5
...                               ...       ...          ...
Wes Craven                       1984      2011           10
Wolfgang Petersen                1981      2006            7
Woody Allen                      1977      2013           18
Zack Snyder                      2004      2016            7
Zhang Yimou                      2002      2014            6

[199 rows x 3 columns]

Approach 2

In [ ]:
data.groupby('director_name')[["year","title"]].aggregate(year_max=('year','max'),year_min=('year','min'), title_count=('title','count'))

                             year_max  year_min  title_count
director_name
Adam McKay                       2015      2004            6
Adam Shankman                    2012      2001            8
Alejandro González Iñárritu      2015      2000            6
Alex Proyas                      2016      1994            5
Alexander Payne                  2013      1999            5
...                               ...       ...          ...
Wes Craven                       2011      1984           10
Wolfgang Petersen                2006      1981            7
Woody Allen                      2013      1977           18
Zack Snyder                      2016      2004            7
Zhang Yimou                      2014      2002            6

[199 rows x 3 columns]

In [ ]:
data_agg

                             year_min  year_max  title_count
director_name
Adam McKay                       2004      2015            6
Adam Shankman                    2001      2012            8
Alejandro González Iñárritu      2000      2015            6
Alex Proyas                      1994      2016            5
Alexander Payne                  1999      2013            5
...                               ...       ...          ...
Wes Craven                       1984      2011           10
Wolfgang Petersen                1981      2006            7
Woody Allen                      1977      2013           18
Zack Snyder                      2004      2016            7
Zhang Yimou                      2002      2014            6

[199 rows x 3 columns]

In [ ]:
data_agg

                             year_min  year_max  title_count
director_name
Adam McKay                       2004      2015            6
Adam Shankman                    2001      2012            8
Alejandro González Iñárritu      2000      2015            6
Alex Proyas                      1994      2016            5
Alexander Payne                  1999      2013            5
...                               ...       ...          ...
Wes Craven                       1984      2011           10
Wolfgang Petersen                1981      2006            7
Woody Allen                      1977      2013           18
Zack Snyder                      2004      2016            7
Zhang Yimou                      2002      2014            6

[199 rows x 3 columns]

In [ ]:
data_agg.reset_index()

                   director_name  year_min  year_max  title_count
0                     Adam McKay      2004      2015            6
1                  Adam Shankman      2001      2012            8
2    Alejandro González Iñárritu      2000      2015            6
3                    Alex Proyas      1994      2016            5
4                Alexander Payne      1999      2013            5
..                           ...       ...       ...          ...
194                   Wes Craven      1984      2011           10
195            Wolfgang Petersen      1981      2006            7
196                  Woody Allen      1977      2013           18
197                  Zack Snyder      2004      2016            7
198                  Zhang Yimou      2002      2014            6

[199 rows x 4 columns]

In [ ]:
data_agg.reset_index(drop = True)

     year_min  year_max  title_count
0        2004      2015            6
1        2001      2012            8
2        2000      2015            6
3        1994      2016            5
4        1999      2013            5
..        ...       ...          ...
194      1984      2011           10
195      1981      2006            7
196      1977      2013           18
197      2004      2016            7
198      2002      2014            6

[199 rows x 3 columns]

#Calculate productivity

In [ ]:
data_agg["yrs_active"] = data_agg["year_max"] - data_agg["year_min"]
data_agg

                             year_min  year_max  title_count  yrs_active
director_name
Adam McKay                       2004      2015            6          11
Adam Shankman                    2001      2012            8          11
Alejandro González Iñárritu      2000      2015            6          15
Alex Proyas                      1994      2016            5          22
Alexander Payne                  1999      2013            5          14
...                               ...       ...          ...         ...
Wes Craven                       1984      2011           10          27
Wolfgang Petersen                1981      2006            7          25
Woody Allen                      1977      2013           18          36
Zack Snyder                      2004      2016            7          12
Zhang Yimou                      2002      2014            6          12

[199 rows x 4 columns]

In [ ]:
data_agg['movie_per_year'] = data_agg['title_count']/data_agg['yrs_active']
data_agg

,year_min,year_max,title_count,yrs_active,movie_per_year
director_name,,,,,
Adam McKay,2004,2015,6,11,0.545455
Adam Shankman,2001,2012,8,11,0.727273
Alejandro González Iñárritu,2000,2015,6,15,0.400000
Alex Proyas,1994,2016,5,22,0.227273
Alexander Payne,1999,2013,5,14,0.357143
...,...,...,...,...,...
Wes Craven,1984,2011,10,27,0.370370
Wolfgang Petersen,1981,2006,7,25,0.280000
Woody Allen,1977,2013,18,36,0.500000
Zack Snyder,2004,2016,7,12,0.583333
Zhang Yimou,2002,2014,6,12,0.500000

In [ ]:
data_agg.sort_values('movie_per_year',ascending=False)

                  year_min  year_max  title_count  yrs_active  movie_per_year
director_name
Tyler Perry           2006      2013            9           7        1.285714
Jason Friedberg       2006      2010            5           4        1.250000
Shawn Levy            2002      2014           11          12        0.916667
Robert Rodriguez      1992      2014           16          22        0.727273
Adam Shankman         2001      2012            8          11        0.727273
...                    ...       ...          ...         ...             ...
Lawrence Kasdan       1985      2012            5          27        0.185185
Luc Besson            1985      2014            5          29        0.172414
Michael Apted         1980      2010            5          30        0.166667
Robert Redford        1980      2010            5          30        0.166667
Sidney Lumet          1976      2006            5          30        0.166667

[199 rows x 5 columns]